/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gpu_channelizer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(34aff827346e6a1019762cb8693efadc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <wifigpu/gpu_channelizer.h>
// pydoc.h is automatically generated in the build directory
#include <gpu_channelizer_pydoc.h>

void bind_gpu_channelizer(py::module& m)
{

    using gpu_channelizer    = ::gr::wifigpu::gpu_channelizer;


    py::class_<gpu_channelizer, gr::block, gr::basic_block,
        std::shared_ptr<gpu_channelizer>>(m, "gpu_channelizer", D(gpu_channelizer))

        .def(py::init(&gpu_channelizer::make),
           py::arg("nchans"),
           py::arg("taps"),
           D(gpu_channelizer,make)
        )
        



        ;




}








