/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tp_decode_mac.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bb3ecb1c9c22a97c02369a848fa046a7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <wifigpu/tp_decode_mac.h>
// pydoc.h is automatically generated in the build directory
#include <tp_decode_mac_pydoc.h>

void bind_tp_decode_mac(py::module& m)
{

    using tp_decode_mac    = ::gr::wifigpu::tp_decode_mac;


    py::class_<tp_decode_mac, gr::block, gr::basic_block,
        std::shared_ptr<tp_decode_mac>>(m, "tp_decode_mac", D(tp_decode_mac))

        .def(py::init(&tp_decode_mac::make),
           py::arg("num_threads"),
           py::arg("queue_depth"),
           py::arg("log") = false,
           py::arg("debug") = false,
           D(tp_decode_mac,make)
        )
        



        ;




}








